//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from C:\Users\Leandro\Desktop\Compiler\CoolCompiler\ANTLR\COOL.g4 by ANTLR 4.7.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using System.Diagnostics;
using System.Collections.Generic;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.1")]
[System.CLSCompliant(false)]
public partial class COOLParser : Parser {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, T__1=2, T__2=3, T__3=4, T__4=5, T__5=6, T__6=7, T__7=8, T__8=9, 
		CLASS=10, ELSE=11, FALSE=12, FI=13, IF=14, IN=15, INHERITS=16, ISVOID=17, 
		LET=18, LOOP=19, POOL=20, THEN=21, WHILE=22, CASE=23, ESAC=24, NEW=25, 
		OF=26, NOT=27, TRUE=28, STRING=29, INT=30, TYPEID=31, OBJECTID=32, ASSIGNMENT=33, 
		CASE_ARROW=34, ADD=35, MINUS=36, MULTIPLY=37, DIVISION=38, LESS_THAN=39, 
		LESS_EQUAL=40, EQUAL=41, INTEGER_NEGATIVE=42, OPEN_COMMENT=43, CLOSE_COMMENT=44, 
		COMMENT=45, ONE_LINE_COMMENT=46, WHITESPACE=47;
	public const int
		RULE_program = 0, RULE_programBlocks = 1, RULE_classDefine = 2, RULE_feature = 3, 
		RULE_formal = 4, RULE_expression = 5;
	public static readonly string[] ruleNames = {
		"program", "programBlocks", "classDefine", "feature", "formal", "expression"
	};

	private static readonly string[] _LiteralNames = {
		null, "';'", "'{'", "'}'", "'('", "','", "')'", "':'", "'@'", "'.'", null, 
		null, null, null, null, null, null, null, null, null, null, null, null, 
		null, null, null, null, null, null, null, null, null, null, "'<-'", "'=>'", 
		"'+'", "'-'", "'*'", "'/'", "'<'", "'<='", "'='", "'~'", "'(*'", "'*)'"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, null, null, null, null, null, null, null, "CLASS", "ELSE", 
		"FALSE", "FI", "IF", "IN", "INHERITS", "ISVOID", "LET", "LOOP", "POOL", 
		"THEN", "WHILE", "CASE", "ESAC", "NEW", "OF", "NOT", "TRUE", "STRING", 
		"INT", "TYPEID", "OBJECTID", "ASSIGNMENT", "CASE_ARROW", "ADD", "MINUS", 
		"MULTIPLY", "DIVISION", "LESS_THAN", "LESS_EQUAL", "EQUAL", "INTEGER_NEGATIVE", 
		"OPEN_COMMENT", "CLOSE_COMMENT", "COMMENT", "ONE_LINE_COMMENT", "WHITESPACE"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "COOL.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static COOLParser() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}

		public COOLParser(ITokenStream input) : this(input, Console.Out, Console.Error) { }

		public COOLParser(ITokenStream input, TextWriter output, TextWriter errorOutput)
		: base(input, output, errorOutput)
	{
		Interpreter = new ParserATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}
	public partial class ProgramContext : ParserRuleContext {
		public ProgramBlocksContext programBlocks() {
			return GetRuleContext<ProgramBlocksContext>(0);
		}
		public ProgramContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_program; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICOOLVisitor<TResult> typedVisitor = visitor as ICOOLVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitProgram(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ProgramContext program() {
		ProgramContext _localctx = new ProgramContext(Context, State);
		EnterRule(_localctx, 0, RULE_program);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 12; programBlocks();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ProgramBlocksContext : ParserRuleContext {
		public ProgramBlocksContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_programBlocks; } }
	 
		public ProgramBlocksContext() { }
		public virtual void CopyFrom(ProgramBlocksContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class ClassesContext : ProgramBlocksContext {
		public ClassDefineContext classDefine() {
			return GetRuleContext<ClassDefineContext>(0);
		}
		public ProgramBlocksContext programBlocks() {
			return GetRuleContext<ProgramBlocksContext>(0);
		}
		public ClassesContext(ProgramBlocksContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICOOLVisitor<TResult> typedVisitor = visitor as ICOOLVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitClasses(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class EofContext : ProgramBlocksContext {
		public ITerminalNode Eof() { return GetToken(COOLParser.Eof, 0); }
		public EofContext(ProgramBlocksContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICOOLVisitor<TResult> typedVisitor = visitor as ICOOLVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitEof(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ProgramBlocksContext programBlocks() {
		ProgramBlocksContext _localctx = new ProgramBlocksContext(Context, State);
		EnterRule(_localctx, 2, RULE_programBlocks);
		try {
			State = 19;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case CLASS:
				_localctx = new ClassesContext(_localctx);
				EnterOuterAlt(_localctx, 1);
				{
				State = 14; classDefine();
				State = 15; Match(T__0);
				State = 16; programBlocks();
				}
				break;
			case Eof:
				_localctx = new EofContext(_localctx);
				EnterOuterAlt(_localctx, 2);
				{
				State = 18; Match(Eof);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ClassDefineContext : ParserRuleContext {
		public ITerminalNode CLASS() { return GetToken(COOLParser.CLASS, 0); }
		public ITerminalNode[] TYPEID() { return GetTokens(COOLParser.TYPEID); }
		public ITerminalNode TYPEID(int i) {
			return GetToken(COOLParser.TYPEID, i);
		}
		public ITerminalNode INHERITS() { return GetToken(COOLParser.INHERITS, 0); }
		public FeatureContext[] feature() {
			return GetRuleContexts<FeatureContext>();
		}
		public FeatureContext feature(int i) {
			return GetRuleContext<FeatureContext>(i);
		}
		public ClassDefineContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_classDefine; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICOOLVisitor<TResult> typedVisitor = visitor as ICOOLVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitClassDefine(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ClassDefineContext classDefine() {
		ClassDefineContext _localctx = new ClassDefineContext(Context, State);
		EnterRule(_localctx, 4, RULE_classDefine);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 21; Match(CLASS);
			State = 22; Match(TYPEID);
			State = 25;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==INHERITS) {
				{
				State = 23; Match(INHERITS);
				State = 24; Match(TYPEID);
				}
			}

			State = 27; Match(T__1);
			State = 33;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==OBJECTID) {
				{
				{
				State = 28; feature();
				State = 29; Match(T__0);
				}
				}
				State = 35;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 36; Match(T__2);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class FeatureContext : ParserRuleContext {
		public FeatureContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_feature; } }
	 
		public FeatureContext() { }
		public virtual void CopyFrom(FeatureContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class MethodContext : FeatureContext {
		public ITerminalNode OBJECTID() { return GetToken(COOLParser.OBJECTID, 0); }
		public ITerminalNode TYPEID() { return GetToken(COOLParser.TYPEID, 0); }
		public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		public FormalContext[] formal() {
			return GetRuleContexts<FormalContext>();
		}
		public FormalContext formal(int i) {
			return GetRuleContext<FormalContext>(i);
		}
		public MethodContext(FeatureContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICOOLVisitor<TResult> typedVisitor = visitor as ICOOLVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitMethod(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class PropertyContext : FeatureContext {
		public ITerminalNode OBJECTID() { return GetToken(COOLParser.OBJECTID, 0); }
		public ITerminalNode TYPEID() { return GetToken(COOLParser.TYPEID, 0); }
		public ITerminalNode ASSIGNMENT() { return GetToken(COOLParser.ASSIGNMENT, 0); }
		public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		public PropertyContext(FeatureContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICOOLVisitor<TResult> typedVisitor = visitor as ICOOLVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitProperty(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public FeatureContext feature() {
		FeatureContext _localctx = new FeatureContext(Context, State);
		EnterRule(_localctx, 6, RULE_feature);
		int _la;
		try {
			State = 67;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,6,Context) ) {
			case 1:
				_localctx = new MethodContext(_localctx);
				EnterOuterAlt(_localctx, 1);
				{
				State = 38; Match(OBJECTID);
				State = 39; Match(T__3);
				State = 50;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				while (_la==OBJECTID) {
					{
					{
					State = 40; formal();
					State = 45;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
					while (_la==T__4) {
						{
						{
						State = 41; Match(T__4);
						State = 42; formal();
						}
						}
						State = 47;
						ErrorHandler.Sync(this);
						_la = TokenStream.LA(1);
					}
					}
					}
					State = 52;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				}
				State = 53; Match(T__5);
				State = 54; Match(T__6);
				State = 55; Match(TYPEID);
				State = 56; Match(T__1);
				State = 57; expression(0);
				State = 58; Match(T__2);
				}
				break;
			case 2:
				_localctx = new PropertyContext(_localctx);
				EnterOuterAlt(_localctx, 2);
				{
				State = 60; Match(OBJECTID);
				State = 61; Match(T__6);
				State = 62; Match(TYPEID);
				State = 65;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if (_la==ASSIGNMENT) {
					{
					State = 63; Match(ASSIGNMENT);
					State = 64; expression(0);
					}
				}

				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class FormalContext : ParserRuleContext {
		public ITerminalNode OBJECTID() { return GetToken(COOLParser.OBJECTID, 0); }
		public ITerminalNode TYPEID() { return GetToken(COOLParser.TYPEID, 0); }
		public FormalContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_formal; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICOOLVisitor<TResult> typedVisitor = visitor as ICOOLVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFormal(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public FormalContext formal() {
		FormalContext _localctx = new FormalContext(Context, State);
		EnterRule(_localctx, 8, RULE_formal);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 69; Match(OBJECTID);
			State = 70; Match(T__6);
			State = 71; Match(TYPEID);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ExpressionContext : ParserRuleContext {
		public ExpressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_expression; } }
	 
		public ExpressionContext() { }
		public virtual void CopyFrom(ExpressionContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class LetInContext : ExpressionContext {
		public ITerminalNode LET() { return GetToken(COOLParser.LET, 0); }
		public ITerminalNode[] OBJECTID() { return GetTokens(COOLParser.OBJECTID); }
		public ITerminalNode OBJECTID(int i) {
			return GetToken(COOLParser.OBJECTID, i);
		}
		public ITerminalNode[] TYPEID() { return GetTokens(COOLParser.TYPEID); }
		public ITerminalNode TYPEID(int i) {
			return GetToken(COOLParser.TYPEID, i);
		}
		public ITerminalNode IN() { return GetToken(COOLParser.IN, 0); }
		public ExpressionContext[] expression() {
			return GetRuleContexts<ExpressionContext>();
		}
		public ExpressionContext expression(int i) {
			return GetRuleContext<ExpressionContext>(i);
		}
		public ITerminalNode[] ASSIGNMENT() { return GetTokens(COOLParser.ASSIGNMENT); }
		public ITerminalNode ASSIGNMENT(int i) {
			return GetToken(COOLParser.ASSIGNMENT, i);
		}
		public LetInContext(ExpressionContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICOOLVisitor<TResult> typedVisitor = visitor as ICOOLVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitLetIn(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class MinusContext : ExpressionContext {
		public ExpressionContext[] expression() {
			return GetRuleContexts<ExpressionContext>();
		}
		public ExpressionContext expression(int i) {
			return GetRuleContext<ExpressionContext>(i);
		}
		public ITerminalNode MINUS() { return GetToken(COOLParser.MINUS, 0); }
		public MinusContext(ExpressionContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICOOLVisitor<TResult> typedVisitor = visitor as ICOOLVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitMinus(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class StringContext : ExpressionContext {
		public ITerminalNode STRING() { return GetToken(COOLParser.STRING, 0); }
		public StringContext(ExpressionContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICOOLVisitor<TResult> typedVisitor = visitor as ICOOLVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitString(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class IsvoidContext : ExpressionContext {
		public ITerminalNode ISVOID() { return GetToken(COOLParser.ISVOID, 0); }
		public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		public IsvoidContext(ExpressionContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICOOLVisitor<TResult> typedVisitor = visitor as ICOOLVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitIsvoid(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class WhileContext : ExpressionContext {
		public ITerminalNode WHILE() { return GetToken(COOLParser.WHILE, 0); }
		public ExpressionContext[] expression() {
			return GetRuleContexts<ExpressionContext>();
		}
		public ExpressionContext expression(int i) {
			return GetRuleContext<ExpressionContext>(i);
		}
		public ITerminalNode LOOP() { return GetToken(COOLParser.LOOP, 0); }
		public ITerminalNode POOL() { return GetToken(COOLParser.POOL, 0); }
		public WhileContext(ExpressionContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICOOLVisitor<TResult> typedVisitor = visitor as ICOOLVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitWhile(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class DivisionContext : ExpressionContext {
		public ExpressionContext[] expression() {
			return GetRuleContexts<ExpressionContext>();
		}
		public ExpressionContext expression(int i) {
			return GetRuleContext<ExpressionContext>(i);
		}
		public ITerminalNode DIVISION() { return GetToken(COOLParser.DIVISION, 0); }
		public DivisionContext(ExpressionContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICOOLVisitor<TResult> typedVisitor = visitor as ICOOLVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitDivision(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class NegativeContext : ExpressionContext {
		public ITerminalNode INTEGER_NEGATIVE() { return GetToken(COOLParser.INTEGER_NEGATIVE, 0); }
		public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		public NegativeContext(ExpressionContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICOOLVisitor<TResult> typedVisitor = visitor as ICOOLVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitNegative(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class BoolNotContext : ExpressionContext {
		public ITerminalNode NOT() { return GetToken(COOLParser.NOT, 0); }
		public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		public BoolNotContext(ExpressionContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICOOLVisitor<TResult> typedVisitor = visitor as ICOOLVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitBoolNot(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class LessThanContext : ExpressionContext {
		public ExpressionContext[] expression() {
			return GetRuleContexts<ExpressionContext>();
		}
		public ExpressionContext expression(int i) {
			return GetRuleContext<ExpressionContext>(i);
		}
		public ITerminalNode LESS_THAN() { return GetToken(COOLParser.LESS_THAN, 0); }
		public LessThanContext(ExpressionContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICOOLVisitor<TResult> typedVisitor = visitor as ICOOLVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitLessThan(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class BlockContext : ExpressionContext {
		public ExpressionContext[] expression() {
			return GetRuleContexts<ExpressionContext>();
		}
		public ExpressionContext expression(int i) {
			return GetRuleContext<ExpressionContext>(i);
		}
		public BlockContext(ExpressionContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICOOLVisitor<TResult> typedVisitor = visitor as ICOOLVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitBlock(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class IdContext : ExpressionContext {
		public ITerminalNode OBJECTID() { return GetToken(COOLParser.OBJECTID, 0); }
		public IdContext(ExpressionContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICOOLVisitor<TResult> typedVisitor = visitor as ICOOLVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitId(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class MultiplyContext : ExpressionContext {
		public ExpressionContext[] expression() {
			return GetRuleContexts<ExpressionContext>();
		}
		public ExpressionContext expression(int i) {
			return GetRuleContext<ExpressionContext>(i);
		}
		public ITerminalNode MULTIPLY() { return GetToken(COOLParser.MULTIPLY, 0); }
		public MultiplyContext(ExpressionContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICOOLVisitor<TResult> typedVisitor = visitor as ICOOLVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitMultiply(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class IfContext : ExpressionContext {
		public ITerminalNode IF() { return GetToken(COOLParser.IF, 0); }
		public ExpressionContext[] expression() {
			return GetRuleContexts<ExpressionContext>();
		}
		public ExpressionContext expression(int i) {
			return GetRuleContext<ExpressionContext>(i);
		}
		public ITerminalNode THEN() { return GetToken(COOLParser.THEN, 0); }
		public ITerminalNode ELSE() { return GetToken(COOLParser.ELSE, 0); }
		public ITerminalNode FI() { return GetToken(COOLParser.FI, 0); }
		public IfContext(ExpressionContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICOOLVisitor<TResult> typedVisitor = visitor as ICOOLVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitIf(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class CaseContext : ExpressionContext {
		public ITerminalNode CASE() { return GetToken(COOLParser.CASE, 0); }
		public ExpressionContext[] expression() {
			return GetRuleContexts<ExpressionContext>();
		}
		public ExpressionContext expression(int i) {
			return GetRuleContext<ExpressionContext>(i);
		}
		public ITerminalNode OF() { return GetToken(COOLParser.OF, 0); }
		public ITerminalNode ESAC() { return GetToken(COOLParser.ESAC, 0); }
		public ITerminalNode[] OBJECTID() { return GetTokens(COOLParser.OBJECTID); }
		public ITerminalNode OBJECTID(int i) {
			return GetToken(COOLParser.OBJECTID, i);
		}
		public ITerminalNode[] TYPEID() { return GetTokens(COOLParser.TYPEID); }
		public ITerminalNode TYPEID(int i) {
			return GetToken(COOLParser.TYPEID, i);
		}
		public ITerminalNode[] CASE_ARROW() { return GetTokens(COOLParser.CASE_ARROW); }
		public ITerminalNode CASE_ARROW(int i) {
			return GetToken(COOLParser.CASE_ARROW, i);
		}
		public CaseContext(ExpressionContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICOOLVisitor<TResult> typedVisitor = visitor as ICOOLVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitCase(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class OwnMethodCallContext : ExpressionContext {
		public ITerminalNode OBJECTID() { return GetToken(COOLParser.OBJECTID, 0); }
		public ExpressionContext[] expression() {
			return GetRuleContexts<ExpressionContext>();
		}
		public ExpressionContext expression(int i) {
			return GetRuleContext<ExpressionContext>(i);
		}
		public OwnMethodCallContext(ExpressionContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICOOLVisitor<TResult> typedVisitor = visitor as ICOOLVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitOwnMethodCall(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class AddContext : ExpressionContext {
		public ExpressionContext[] expression() {
			return GetRuleContexts<ExpressionContext>();
		}
		public ExpressionContext expression(int i) {
			return GetRuleContext<ExpressionContext>(i);
		}
		public ITerminalNode ADD() { return GetToken(COOLParser.ADD, 0); }
		public AddContext(ExpressionContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICOOLVisitor<TResult> typedVisitor = visitor as ICOOLVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitAdd(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class NewContext : ExpressionContext {
		public ITerminalNode NEW() { return GetToken(COOLParser.NEW, 0); }
		public ITerminalNode TYPEID() { return GetToken(COOLParser.TYPEID, 0); }
		public NewContext(ExpressionContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICOOLVisitor<TResult> typedVisitor = visitor as ICOOLVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitNew(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class ParenthesesContext : ExpressionContext {
		public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		public ParenthesesContext(ExpressionContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICOOLVisitor<TResult> typedVisitor = visitor as ICOOLVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitParentheses(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class AssignmentContext : ExpressionContext {
		public ITerminalNode OBJECTID() { return GetToken(COOLParser.OBJECTID, 0); }
		public ITerminalNode ASSIGNMENT() { return GetToken(COOLParser.ASSIGNMENT, 0); }
		public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		public AssignmentContext(ExpressionContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICOOLVisitor<TResult> typedVisitor = visitor as ICOOLVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitAssignment(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class FalseContext : ExpressionContext {
		public ITerminalNode FALSE() { return GetToken(COOLParser.FALSE, 0); }
		public FalseContext(ExpressionContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICOOLVisitor<TResult> typedVisitor = visitor as ICOOLVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFalse(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class IntContext : ExpressionContext {
		public ITerminalNode INT() { return GetToken(COOLParser.INT, 0); }
		public IntContext(ExpressionContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICOOLVisitor<TResult> typedVisitor = visitor as ICOOLVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitInt(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class EqualContext : ExpressionContext {
		public ExpressionContext[] expression() {
			return GetRuleContexts<ExpressionContext>();
		}
		public ExpressionContext expression(int i) {
			return GetRuleContext<ExpressionContext>(i);
		}
		public ITerminalNode EQUAL() { return GetToken(COOLParser.EQUAL, 0); }
		public EqualContext(ExpressionContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICOOLVisitor<TResult> typedVisitor = visitor as ICOOLVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitEqual(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class TrueContext : ExpressionContext {
		public ITerminalNode TRUE() { return GetToken(COOLParser.TRUE, 0); }
		public TrueContext(ExpressionContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICOOLVisitor<TResult> typedVisitor = visitor as ICOOLVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitTrue(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class LessEqualContext : ExpressionContext {
		public ExpressionContext[] expression() {
			return GetRuleContexts<ExpressionContext>();
		}
		public ExpressionContext expression(int i) {
			return GetRuleContext<ExpressionContext>(i);
		}
		public ITerminalNode LESS_EQUAL() { return GetToken(COOLParser.LESS_EQUAL, 0); }
		public LessEqualContext(ExpressionContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICOOLVisitor<TResult> typedVisitor = visitor as ICOOLVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitLessEqual(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class MethodCallContext : ExpressionContext {
		public ExpressionContext[] expression() {
			return GetRuleContexts<ExpressionContext>();
		}
		public ExpressionContext expression(int i) {
			return GetRuleContext<ExpressionContext>(i);
		}
		public ITerminalNode OBJECTID() { return GetToken(COOLParser.OBJECTID, 0); }
		public ITerminalNode TYPEID() { return GetToken(COOLParser.TYPEID, 0); }
		public MethodCallContext(ExpressionContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICOOLVisitor<TResult> typedVisitor = visitor as ICOOLVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitMethodCall(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ExpressionContext expression() {
		return expression(0);
	}

	private ExpressionContext expression(int _p) {
		ParserRuleContext _parentctx = Context;
		int _parentState = State;
		ExpressionContext _localctx = new ExpressionContext(Context, _parentState);
		ExpressionContext _prevctx = _localctx;
		int _startState = 10;
		EnterRecursionRule(_localctx, 10, RULE_expression, _p);
		int _la;
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 173;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,14,Context) ) {
			case 1:
				{
				_localctx = new OwnMethodCallContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;

				State = 74; Match(OBJECTID);
				State = 75; Match(T__3);
				State = 86;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				while ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << T__1) | (1L << T__3) | (1L << FALSE) | (1L << IF) | (1L << ISVOID) | (1L << LET) | (1L << WHILE) | (1L << CASE) | (1L << NEW) | (1L << NOT) | (1L << TRUE) | (1L << STRING) | (1L << INT) | (1L << OBJECTID) | (1L << INTEGER_NEGATIVE))) != 0)) {
					{
					{
					State = 76; expression(0);
					State = 81;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
					while (_la==T__4) {
						{
						{
						State = 77; Match(T__4);
						State = 78; expression(0);
						}
						}
						State = 83;
						ErrorHandler.Sync(this);
						_la = TokenStream.LA(1);
					}
					}
					}
					State = 88;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				}
				State = 89; Match(T__5);
				}
				break;
			case 2:
				{
				_localctx = new IfContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 90; Match(IF);
				State = 91; expression(0);
				State = 92; Match(THEN);
				State = 93; expression(0);
				State = 94; Match(ELSE);
				State = 95; expression(0);
				State = 96; Match(FI);
				}
				break;
			case 3:
				{
				_localctx = new WhileContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 98; Match(WHILE);
				State = 99; expression(0);
				State = 100; Match(LOOP);
				State = 101; expression(0);
				State = 102; Match(POOL);
				}
				break;
			case 4:
				{
				_localctx = new BlockContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 104; Match(T__1);
				State = 108;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				do {
					{
					{
					State = 105; expression(0);
					State = 106; Match(T__0);
					}
					}
					State = 110;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				} while ( (((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << T__1) | (1L << T__3) | (1L << FALSE) | (1L << IF) | (1L << ISVOID) | (1L << LET) | (1L << WHILE) | (1L << CASE) | (1L << NEW) | (1L << NOT) | (1L << TRUE) | (1L << STRING) | (1L << INT) | (1L << OBJECTID) | (1L << INTEGER_NEGATIVE))) != 0) );
				State = 112; Match(T__2);
				}
				break;
			case 5:
				{
				_localctx = new LetInContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 114; Match(LET);
				State = 115; Match(OBJECTID);
				State = 116; Match(T__6);
				State = 117; Match(TYPEID);
				State = 120;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if (_la==ASSIGNMENT) {
					{
					State = 118; Match(ASSIGNMENT);
					State = 119; expression(0);
					}
				}

				State = 132;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				while (_la==T__4) {
					{
					{
					State = 122; Match(T__4);
					State = 123; Match(OBJECTID);
					State = 124; Match(T__6);
					State = 125; Match(TYPEID);
					State = 128;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
					if (_la==ASSIGNMENT) {
						{
						State = 126; Match(ASSIGNMENT);
						State = 127; expression(0);
						}
					}

					}
					}
					State = 134;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				}
				State = 135; Match(IN);
				State = 136; expression(20);
				}
				break;
			case 6:
				{
				_localctx = new CaseContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 137; Match(CASE);
				State = 138; expression(0);
				State = 139; Match(OF);
				State = 147;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				do {
					{
					{
					State = 140; Match(OBJECTID);
					State = 141; Match(T__6);
					State = 142; Match(TYPEID);
					State = 143; Match(CASE_ARROW);
					State = 144; expression(0);
					State = 145; Match(T__0);
					}
					}
					State = 149;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				} while ( _la==OBJECTID );
				State = 151; Match(ESAC);
				}
				break;
			case 7:
				{
				_localctx = new NewContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 153; Match(NEW);
				State = 154; Match(TYPEID);
				}
				break;
			case 8:
				{
				_localctx = new NegativeContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 155; Match(INTEGER_NEGATIVE);
				State = 156; expression(17);
				}
				break;
			case 9:
				{
				_localctx = new IsvoidContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 157; Match(ISVOID);
				State = 158; expression(16);
				}
				break;
			case 10:
				{
				_localctx = new BoolNotContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 159; Match(NOT);
				State = 160; expression(8);
				}
				break;
			case 11:
				{
				_localctx = new ParenthesesContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 161; Match(T__3);
				State = 162; expression(0);
				State = 163; Match(T__5);
				}
				break;
			case 12:
				{
				_localctx = new IdContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 165; Match(OBJECTID);
				}
				break;
			case 13:
				{
				_localctx = new IntContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 166; Match(INT);
				}
				break;
			case 14:
				{
				_localctx = new StringContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 167; Match(STRING);
				}
				break;
			case 15:
				{
				_localctx = new TrueContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 168; Match(TRUE);
				}
				break;
			case 16:
				{
				_localctx = new FalseContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 169; Match(FALSE);
				}
				break;
			case 17:
				{
				_localctx = new AssignmentContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 170; Match(OBJECTID);
				State = 171; Match(ASSIGNMENT);
				State = 172; expression(1);
				}
				break;
			}
			Context.Stop = TokenStream.LT(-1);
			State = 220;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,19,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					if ( ParseListeners!=null )
						TriggerExitRuleEvent();
					_prevctx = _localctx;
					{
					State = 218;
					ErrorHandler.Sync(this);
					switch ( Interpreter.AdaptivePredict(TokenStream,18,Context) ) {
					case 1:
						{
						_localctx = new MultiplyContext(new ExpressionContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_expression);
						State = 175;
						if (!(Precpred(Context, 15))) throw new FailedPredicateException(this, "Precpred(Context, 15)");
						State = 176; Match(MULTIPLY);
						State = 177; expression(16);
						}
						break;
					case 2:
						{
						_localctx = new DivisionContext(new ExpressionContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_expression);
						State = 178;
						if (!(Precpred(Context, 14))) throw new FailedPredicateException(this, "Precpred(Context, 14)");
						State = 179; Match(DIVISION);
						State = 180; expression(15);
						}
						break;
					case 3:
						{
						_localctx = new AddContext(new ExpressionContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_expression);
						State = 181;
						if (!(Precpred(Context, 13))) throw new FailedPredicateException(this, "Precpred(Context, 13)");
						State = 182; Match(ADD);
						State = 183; expression(14);
						}
						break;
					case 4:
						{
						_localctx = new MinusContext(new ExpressionContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_expression);
						State = 184;
						if (!(Precpred(Context, 12))) throw new FailedPredicateException(this, "Precpred(Context, 12)");
						State = 185; Match(MINUS);
						State = 186; expression(13);
						}
						break;
					case 5:
						{
						_localctx = new LessThanContext(new ExpressionContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_expression);
						State = 187;
						if (!(Precpred(Context, 11))) throw new FailedPredicateException(this, "Precpred(Context, 11)");
						State = 188; Match(LESS_THAN);
						State = 189; expression(12);
						}
						break;
					case 6:
						{
						_localctx = new LessEqualContext(new ExpressionContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_expression);
						State = 190;
						if (!(Precpred(Context, 10))) throw new FailedPredicateException(this, "Precpred(Context, 10)");
						State = 191; Match(LESS_EQUAL);
						State = 192; expression(11);
						}
						break;
					case 7:
						{
						_localctx = new EqualContext(new ExpressionContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_expression);
						State = 193;
						if (!(Precpred(Context, 9))) throw new FailedPredicateException(this, "Precpred(Context, 9)");
						State = 194; Match(EQUAL);
						State = 195; expression(10);
						}
						break;
					case 8:
						{
						_localctx = new MethodCallContext(new ExpressionContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_expression);
						State = 196;
						if (!(Precpred(Context, 25))) throw new FailedPredicateException(this, "Precpred(Context, 25)");
						State = 199;
						ErrorHandler.Sync(this);
						_la = TokenStream.LA(1);
						if (_la==T__7) {
							{
							State = 197; Match(T__7);
							State = 198; Match(TYPEID);
							}
						}

						State = 201; Match(T__8);
						State = 202; Match(OBJECTID);
						State = 203; Match(T__3);
						State = 214;
						ErrorHandler.Sync(this);
						_la = TokenStream.LA(1);
						while ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << T__1) | (1L << T__3) | (1L << FALSE) | (1L << IF) | (1L << ISVOID) | (1L << LET) | (1L << WHILE) | (1L << CASE) | (1L << NEW) | (1L << NOT) | (1L << TRUE) | (1L << STRING) | (1L << INT) | (1L << OBJECTID) | (1L << INTEGER_NEGATIVE))) != 0)) {
							{
							{
							State = 204; expression(0);
							State = 209;
							ErrorHandler.Sync(this);
							_la = TokenStream.LA(1);
							while (_la==T__4) {
								{
								{
								State = 205; Match(T__4);
								State = 206; expression(0);
								}
								}
								State = 211;
								ErrorHandler.Sync(this);
								_la = TokenStream.LA(1);
							}
							}
							}
							State = 216;
							ErrorHandler.Sync(this);
							_la = TokenStream.LA(1);
						}
						State = 217; Match(T__5);
						}
						break;
					}
					} 
				}
				State = 222;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,19,Context);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			UnrollRecursionContexts(_parentctx);
		}
		return _localctx;
	}

	public override bool Sempred(RuleContext _localctx, int ruleIndex, int predIndex) {
		switch (ruleIndex) {
		case 5: return expression_sempred((ExpressionContext)_localctx, predIndex);
		}
		return true;
	}
	private bool expression_sempred(ExpressionContext _localctx, int predIndex) {
		switch (predIndex) {
		case 0: return Precpred(Context, 15);
		case 1: return Precpred(Context, 14);
		case 2: return Precpred(Context, 13);
		case 3: return Precpred(Context, 12);
		case 4: return Precpred(Context, 11);
		case 5: return Precpred(Context, 10);
		case 6: return Precpred(Context, 9);
		case 7: return Precpred(Context, 25);
		}
		return true;
	}

	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x3', '\x31', '\xE2', '\x4', '\x2', '\t', '\x2', '\x4', '\x3', 
		'\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', '\x5', '\x4', 
		'\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x3', '\x2', '\x3', '\x2', 
		'\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', 
		'\x5', '\x3', '\x16', '\n', '\x3', '\x3', '\x4', '\x3', '\x4', '\x3', 
		'\x4', '\x3', '\x4', '\x5', '\x4', '\x1C', '\n', '\x4', '\x3', '\x4', 
		'\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\a', '\x4', '\"', '\n', '\x4', 
		'\f', '\x4', '\xE', '\x4', '%', '\v', '\x4', '\x3', '\x4', '\x3', '\x4', 
		'\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', 
		'\a', '\x5', '.', '\n', '\x5', '\f', '\x5', '\xE', '\x5', '\x31', '\v', 
		'\x5', '\a', '\x5', '\x33', '\n', '\x5', '\f', '\x5', '\xE', '\x5', '\x36', 
		'\v', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', 
		'\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', 
		'\x5', '\x3', '\x5', '\x3', '\x5', '\x5', '\x5', '\x44', '\n', '\x5', 
		'\x5', '\x5', '\x46', '\n', '\x5', '\x3', '\x6', '\x3', '\x6', '\x3', 
		'\x6', '\x3', '\x6', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', 
		'\x3', '\a', '\x3', '\a', '\a', '\a', 'R', '\n', '\a', '\f', '\a', '\xE', 
		'\a', 'U', '\v', '\a', '\a', '\a', 'W', '\n', '\a', '\f', '\a', '\xE', 
		'\a', 'Z', '\v', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', 
		'\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', 
		'\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', 
		'\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x6', '\a', 'o', 
		'\n', '\a', '\r', '\a', '\xE', '\a', 'p', '\x3', '\a', '\x3', '\a', '\x3', 
		'\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', 
		'\x5', '\a', '{', '\n', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', 
		'\a', '\x3', '\a', '\x3', '\a', '\x5', '\a', '\x83', '\n', '\a', '\a', 
		'\a', '\x85', '\n', '\a', '\f', '\a', '\xE', '\a', '\x88', '\v', '\a', 
		'\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', 
		'\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', 
		'\x3', '\a', '\x6', '\a', '\x96', '\n', '\a', '\r', '\a', '\xE', '\a', 
		'\x97', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', 
		'\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', 
		'\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', 
		'\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', 
		'\a', '\x5', '\a', '\xB0', '\n', '\a', '\x3', '\a', '\x3', '\a', '\x3', 
		'\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', 
		'\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', 
		'\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', 
		'\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x5', 
		'\a', '\xCA', '\n', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', 
		'\a', '\x3', '\a', '\x3', '\a', '\a', '\a', '\xD2', '\n', '\a', '\f', 
		'\a', '\xE', '\a', '\xD5', '\v', '\a', '\a', '\a', '\xD7', '\n', '\a', 
		'\f', '\a', '\xE', '\a', '\xDA', '\v', '\a', '\x3', '\a', '\a', '\a', 
		'\xDD', '\n', '\a', '\f', '\a', '\xE', '\a', '\xE0', '\v', '\a', '\x3', 
		'\a', '\x2', '\x3', '\f', '\b', '\x2', '\x4', '\x6', '\b', '\n', '\f', 
		'\x2', '\x2', '\x2', '\x104', '\x2', '\xE', '\x3', '\x2', '\x2', '\x2', 
		'\x4', '\x15', '\x3', '\x2', '\x2', '\x2', '\x6', '\x17', '\x3', '\x2', 
		'\x2', '\x2', '\b', '\x45', '\x3', '\x2', '\x2', '\x2', '\n', 'G', '\x3', 
		'\x2', '\x2', '\x2', '\f', '\xAF', '\x3', '\x2', '\x2', '\x2', '\xE', 
		'\xF', '\x5', '\x4', '\x3', '\x2', '\xF', '\x3', '\x3', '\x2', '\x2', 
		'\x2', '\x10', '\x11', '\x5', '\x6', '\x4', '\x2', '\x11', '\x12', '\a', 
		'\x3', '\x2', '\x2', '\x12', '\x13', '\x5', '\x4', '\x3', '\x2', '\x13', 
		'\x16', '\x3', '\x2', '\x2', '\x2', '\x14', '\x16', '\a', '\x2', '\x2', 
		'\x3', '\x15', '\x10', '\x3', '\x2', '\x2', '\x2', '\x15', '\x14', '\x3', 
		'\x2', '\x2', '\x2', '\x16', '\x5', '\x3', '\x2', '\x2', '\x2', '\x17', 
		'\x18', '\a', '\f', '\x2', '\x2', '\x18', '\x1B', '\a', '!', '\x2', '\x2', 
		'\x19', '\x1A', '\a', '\x12', '\x2', '\x2', '\x1A', '\x1C', '\a', '!', 
		'\x2', '\x2', '\x1B', '\x19', '\x3', '\x2', '\x2', '\x2', '\x1B', '\x1C', 
		'\x3', '\x2', '\x2', '\x2', '\x1C', '\x1D', '\x3', '\x2', '\x2', '\x2', 
		'\x1D', '#', '\a', '\x4', '\x2', '\x2', '\x1E', '\x1F', '\x5', '\b', '\x5', 
		'\x2', '\x1F', ' ', '\a', '\x3', '\x2', '\x2', ' ', '\"', '\x3', '\x2', 
		'\x2', '\x2', '!', '\x1E', '\x3', '\x2', '\x2', '\x2', '\"', '%', '\x3', 
		'\x2', '\x2', '\x2', '#', '!', '\x3', '\x2', '\x2', '\x2', '#', '$', '\x3', 
		'\x2', '\x2', '\x2', '$', '&', '\x3', '\x2', '\x2', '\x2', '%', '#', '\x3', 
		'\x2', '\x2', '\x2', '&', '\'', '\a', '\x5', '\x2', '\x2', '\'', '\a', 
		'\x3', '\x2', '\x2', '\x2', '(', ')', '\a', '\"', '\x2', '\x2', ')', '\x34', 
		'\a', '\x6', '\x2', '\x2', '*', '/', '\x5', '\n', '\x6', '\x2', '+', ',', 
		'\a', '\a', '\x2', '\x2', ',', '.', '\x5', '\n', '\x6', '\x2', '-', '+', 
		'\x3', '\x2', '\x2', '\x2', '.', '\x31', '\x3', '\x2', '\x2', '\x2', '/', 
		'-', '\x3', '\x2', '\x2', '\x2', '/', '\x30', '\x3', '\x2', '\x2', '\x2', 
		'\x30', '\x33', '\x3', '\x2', '\x2', '\x2', '\x31', '/', '\x3', '\x2', 
		'\x2', '\x2', '\x32', '*', '\x3', '\x2', '\x2', '\x2', '\x33', '\x36', 
		'\x3', '\x2', '\x2', '\x2', '\x34', '\x32', '\x3', '\x2', '\x2', '\x2', 
		'\x34', '\x35', '\x3', '\x2', '\x2', '\x2', '\x35', '\x37', '\x3', '\x2', 
		'\x2', '\x2', '\x36', '\x34', '\x3', '\x2', '\x2', '\x2', '\x37', '\x38', 
		'\a', '\b', '\x2', '\x2', '\x38', '\x39', '\a', '\t', '\x2', '\x2', '\x39', 
		':', '\a', '!', '\x2', '\x2', ':', ';', '\a', '\x4', '\x2', '\x2', ';', 
		'<', '\x5', '\f', '\a', '\x2', '<', '=', '\a', '\x5', '\x2', '\x2', '=', 
		'\x46', '\x3', '\x2', '\x2', '\x2', '>', '?', '\a', '\"', '\x2', '\x2', 
		'?', '@', '\a', '\t', '\x2', '\x2', '@', '\x43', '\a', '!', '\x2', '\x2', 
		'\x41', '\x42', '\a', '#', '\x2', '\x2', '\x42', '\x44', '\x5', '\f', 
		'\a', '\x2', '\x43', '\x41', '\x3', '\x2', '\x2', '\x2', '\x43', '\x44', 
		'\x3', '\x2', '\x2', '\x2', '\x44', '\x46', '\x3', '\x2', '\x2', '\x2', 
		'\x45', '(', '\x3', '\x2', '\x2', '\x2', '\x45', '>', '\x3', '\x2', '\x2', 
		'\x2', '\x46', '\t', '\x3', '\x2', '\x2', '\x2', 'G', 'H', '\a', '\"', 
		'\x2', '\x2', 'H', 'I', '\a', '\t', '\x2', '\x2', 'I', 'J', '\a', '!', 
		'\x2', '\x2', 'J', '\v', '\x3', '\x2', '\x2', '\x2', 'K', 'L', '\b', '\a', 
		'\x1', '\x2', 'L', 'M', '\a', '\"', '\x2', '\x2', 'M', 'X', '\a', '\x6', 
		'\x2', '\x2', 'N', 'S', '\x5', '\f', '\a', '\x2', 'O', 'P', '\a', '\a', 
		'\x2', '\x2', 'P', 'R', '\x5', '\f', '\a', '\x2', 'Q', 'O', '\x3', '\x2', 
		'\x2', '\x2', 'R', 'U', '\x3', '\x2', '\x2', '\x2', 'S', 'Q', '\x3', '\x2', 
		'\x2', '\x2', 'S', 'T', '\x3', '\x2', '\x2', '\x2', 'T', 'W', '\x3', '\x2', 
		'\x2', '\x2', 'U', 'S', '\x3', '\x2', '\x2', '\x2', 'V', 'N', '\x3', '\x2', 
		'\x2', '\x2', 'W', 'Z', '\x3', '\x2', '\x2', '\x2', 'X', 'V', '\x3', '\x2', 
		'\x2', '\x2', 'X', 'Y', '\x3', '\x2', '\x2', '\x2', 'Y', '[', '\x3', '\x2', 
		'\x2', '\x2', 'Z', 'X', '\x3', '\x2', '\x2', '\x2', '[', '\xB0', '\a', 
		'\b', '\x2', '\x2', '\\', ']', '\a', '\x10', '\x2', '\x2', ']', '^', '\x5', 
		'\f', '\a', '\x2', '^', '_', '\a', '\x17', '\x2', '\x2', '_', '`', '\x5', 
		'\f', '\a', '\x2', '`', '\x61', '\a', '\r', '\x2', '\x2', '\x61', '\x62', 
		'\x5', '\f', '\a', '\x2', '\x62', '\x63', '\a', '\xF', '\x2', '\x2', '\x63', 
		'\xB0', '\x3', '\x2', '\x2', '\x2', '\x64', '\x65', '\a', '\x18', '\x2', 
		'\x2', '\x65', '\x66', '\x5', '\f', '\a', '\x2', '\x66', 'g', '\a', '\x15', 
		'\x2', '\x2', 'g', 'h', '\x5', '\f', '\a', '\x2', 'h', 'i', '\a', '\x16', 
		'\x2', '\x2', 'i', '\xB0', '\x3', '\x2', '\x2', '\x2', 'j', 'n', '\a', 
		'\x4', '\x2', '\x2', 'k', 'l', '\x5', '\f', '\a', '\x2', 'l', 'm', '\a', 
		'\x3', '\x2', '\x2', 'm', 'o', '\x3', '\x2', '\x2', '\x2', 'n', 'k', '\x3', 
		'\x2', '\x2', '\x2', 'o', 'p', '\x3', '\x2', '\x2', '\x2', 'p', 'n', '\x3', 
		'\x2', '\x2', '\x2', 'p', 'q', '\x3', '\x2', '\x2', '\x2', 'q', 'r', '\x3', 
		'\x2', '\x2', '\x2', 'r', 's', '\a', '\x5', '\x2', '\x2', 's', '\xB0', 
		'\x3', '\x2', '\x2', '\x2', 't', 'u', '\a', '\x14', '\x2', '\x2', 'u', 
		'v', '\a', '\"', '\x2', '\x2', 'v', 'w', '\a', '\t', '\x2', '\x2', 'w', 
		'z', '\a', '!', '\x2', '\x2', 'x', 'y', '\a', '#', '\x2', '\x2', 'y', 
		'{', '\x5', '\f', '\a', '\x2', 'z', 'x', '\x3', '\x2', '\x2', '\x2', 'z', 
		'{', '\x3', '\x2', '\x2', '\x2', '{', '\x86', '\x3', '\x2', '\x2', '\x2', 
		'|', '}', '\a', '\a', '\x2', '\x2', '}', '~', '\a', '\"', '\x2', '\x2', 
		'~', '\x7F', '\a', '\t', '\x2', '\x2', '\x7F', '\x82', '\a', '!', '\x2', 
		'\x2', '\x80', '\x81', '\a', '#', '\x2', '\x2', '\x81', '\x83', '\x5', 
		'\f', '\a', '\x2', '\x82', '\x80', '\x3', '\x2', '\x2', '\x2', '\x82', 
		'\x83', '\x3', '\x2', '\x2', '\x2', '\x83', '\x85', '\x3', '\x2', '\x2', 
		'\x2', '\x84', '|', '\x3', '\x2', '\x2', '\x2', '\x85', '\x88', '\x3', 
		'\x2', '\x2', '\x2', '\x86', '\x84', '\x3', '\x2', '\x2', '\x2', '\x86', 
		'\x87', '\x3', '\x2', '\x2', '\x2', '\x87', '\x89', '\x3', '\x2', '\x2', 
		'\x2', '\x88', '\x86', '\x3', '\x2', '\x2', '\x2', '\x89', '\x8A', '\a', 
		'\x11', '\x2', '\x2', '\x8A', '\xB0', '\x5', '\f', '\a', '\x16', '\x8B', 
		'\x8C', '\a', '\x19', '\x2', '\x2', '\x8C', '\x8D', '\x5', '\f', '\a', 
		'\x2', '\x8D', '\x95', '\a', '\x1C', '\x2', '\x2', '\x8E', '\x8F', '\a', 
		'\"', '\x2', '\x2', '\x8F', '\x90', '\a', '\t', '\x2', '\x2', '\x90', 
		'\x91', '\a', '!', '\x2', '\x2', '\x91', '\x92', '\a', '$', '\x2', '\x2', 
		'\x92', '\x93', '\x5', '\f', '\a', '\x2', '\x93', '\x94', '\a', '\x3', 
		'\x2', '\x2', '\x94', '\x96', '\x3', '\x2', '\x2', '\x2', '\x95', '\x8E', 
		'\x3', '\x2', '\x2', '\x2', '\x96', '\x97', '\x3', '\x2', '\x2', '\x2', 
		'\x97', '\x95', '\x3', '\x2', '\x2', '\x2', '\x97', '\x98', '\x3', '\x2', 
		'\x2', '\x2', '\x98', '\x99', '\x3', '\x2', '\x2', '\x2', '\x99', '\x9A', 
		'\a', '\x1A', '\x2', '\x2', '\x9A', '\xB0', '\x3', '\x2', '\x2', '\x2', 
		'\x9B', '\x9C', '\a', '\x1B', '\x2', '\x2', '\x9C', '\xB0', '\a', '!', 
		'\x2', '\x2', '\x9D', '\x9E', '\a', ',', '\x2', '\x2', '\x9E', '\xB0', 
		'\x5', '\f', '\a', '\x13', '\x9F', '\xA0', '\a', '\x13', '\x2', '\x2', 
		'\xA0', '\xB0', '\x5', '\f', '\a', '\x12', '\xA1', '\xA2', '\a', '\x1D', 
		'\x2', '\x2', '\xA2', '\xB0', '\x5', '\f', '\a', '\n', '\xA3', '\xA4', 
		'\a', '\x6', '\x2', '\x2', '\xA4', '\xA5', '\x5', '\f', '\a', '\x2', '\xA5', 
		'\xA6', '\a', '\b', '\x2', '\x2', '\xA6', '\xB0', '\x3', '\x2', '\x2', 
		'\x2', '\xA7', '\xB0', '\a', '\"', '\x2', '\x2', '\xA8', '\xB0', '\a', 
		' ', '\x2', '\x2', '\xA9', '\xB0', '\a', '\x1F', '\x2', '\x2', '\xAA', 
		'\xB0', '\a', '\x1E', '\x2', '\x2', '\xAB', '\xB0', '\a', '\xE', '\x2', 
		'\x2', '\xAC', '\xAD', '\a', '\"', '\x2', '\x2', '\xAD', '\xAE', '\a', 
		'#', '\x2', '\x2', '\xAE', '\xB0', '\x5', '\f', '\a', '\x3', '\xAF', 'K', 
		'\x3', '\x2', '\x2', '\x2', '\xAF', '\\', '\x3', '\x2', '\x2', '\x2', 
		'\xAF', '\x64', '\x3', '\x2', '\x2', '\x2', '\xAF', 'j', '\x3', '\x2', 
		'\x2', '\x2', '\xAF', 't', '\x3', '\x2', '\x2', '\x2', '\xAF', '\x8B', 
		'\x3', '\x2', '\x2', '\x2', '\xAF', '\x9B', '\x3', '\x2', '\x2', '\x2', 
		'\xAF', '\x9D', '\x3', '\x2', '\x2', '\x2', '\xAF', '\x9F', '\x3', '\x2', 
		'\x2', '\x2', '\xAF', '\xA1', '\x3', '\x2', '\x2', '\x2', '\xAF', '\xA3', 
		'\x3', '\x2', '\x2', '\x2', '\xAF', '\xA7', '\x3', '\x2', '\x2', '\x2', 
		'\xAF', '\xA8', '\x3', '\x2', '\x2', '\x2', '\xAF', '\xA9', '\x3', '\x2', 
		'\x2', '\x2', '\xAF', '\xAA', '\x3', '\x2', '\x2', '\x2', '\xAF', '\xAB', 
		'\x3', '\x2', '\x2', '\x2', '\xAF', '\xAC', '\x3', '\x2', '\x2', '\x2', 
		'\xB0', '\xDE', '\x3', '\x2', '\x2', '\x2', '\xB1', '\xB2', '\f', '\x11', 
		'\x2', '\x2', '\xB2', '\xB3', '\a', '\'', '\x2', '\x2', '\xB3', '\xDD', 
		'\x5', '\f', '\a', '\x12', '\xB4', '\xB5', '\f', '\x10', '\x2', '\x2', 
		'\xB5', '\xB6', '\a', '(', '\x2', '\x2', '\xB6', '\xDD', '\x5', '\f', 
		'\a', '\x11', '\xB7', '\xB8', '\f', '\xF', '\x2', '\x2', '\xB8', '\xB9', 
		'\a', '%', '\x2', '\x2', '\xB9', '\xDD', '\x5', '\f', '\a', '\x10', '\xBA', 
		'\xBB', '\f', '\xE', '\x2', '\x2', '\xBB', '\xBC', '\a', '&', '\x2', '\x2', 
		'\xBC', '\xDD', '\x5', '\f', '\a', '\xF', '\xBD', '\xBE', '\f', '\r', 
		'\x2', '\x2', '\xBE', '\xBF', '\a', ')', '\x2', '\x2', '\xBF', '\xDD', 
		'\x5', '\f', '\a', '\xE', '\xC0', '\xC1', '\f', '\f', '\x2', '\x2', '\xC1', 
		'\xC2', '\a', '*', '\x2', '\x2', '\xC2', '\xDD', '\x5', '\f', '\a', '\r', 
		'\xC3', '\xC4', '\f', '\v', '\x2', '\x2', '\xC4', '\xC5', '\a', '+', '\x2', 
		'\x2', '\xC5', '\xDD', '\x5', '\f', '\a', '\f', '\xC6', '\xC9', '\f', 
		'\x1B', '\x2', '\x2', '\xC7', '\xC8', '\a', '\n', '\x2', '\x2', '\xC8', 
		'\xCA', '\a', '!', '\x2', '\x2', '\xC9', '\xC7', '\x3', '\x2', '\x2', 
		'\x2', '\xC9', '\xCA', '\x3', '\x2', '\x2', '\x2', '\xCA', '\xCB', '\x3', 
		'\x2', '\x2', '\x2', '\xCB', '\xCC', '\a', '\v', '\x2', '\x2', '\xCC', 
		'\xCD', '\a', '\"', '\x2', '\x2', '\xCD', '\xD8', '\a', '\x6', '\x2', 
		'\x2', '\xCE', '\xD3', '\x5', '\f', '\a', '\x2', '\xCF', '\xD0', '\a', 
		'\a', '\x2', '\x2', '\xD0', '\xD2', '\x5', '\f', '\a', '\x2', '\xD1', 
		'\xCF', '\x3', '\x2', '\x2', '\x2', '\xD2', '\xD5', '\x3', '\x2', '\x2', 
		'\x2', '\xD3', '\xD1', '\x3', '\x2', '\x2', '\x2', '\xD3', '\xD4', '\x3', 
		'\x2', '\x2', '\x2', '\xD4', '\xD7', '\x3', '\x2', '\x2', '\x2', '\xD5', 
		'\xD3', '\x3', '\x2', '\x2', '\x2', '\xD6', '\xCE', '\x3', '\x2', '\x2', 
		'\x2', '\xD7', '\xDA', '\x3', '\x2', '\x2', '\x2', '\xD8', '\xD6', '\x3', 
		'\x2', '\x2', '\x2', '\xD8', '\xD9', '\x3', '\x2', '\x2', '\x2', '\xD9', 
		'\xDB', '\x3', '\x2', '\x2', '\x2', '\xDA', '\xD8', '\x3', '\x2', '\x2', 
		'\x2', '\xDB', '\xDD', '\a', '\b', '\x2', '\x2', '\xDC', '\xB1', '\x3', 
		'\x2', '\x2', '\x2', '\xDC', '\xB4', '\x3', '\x2', '\x2', '\x2', '\xDC', 
		'\xB7', '\x3', '\x2', '\x2', '\x2', '\xDC', '\xBA', '\x3', '\x2', '\x2', 
		'\x2', '\xDC', '\xBD', '\x3', '\x2', '\x2', '\x2', '\xDC', '\xC0', '\x3', 
		'\x2', '\x2', '\x2', '\xDC', '\xC3', '\x3', '\x2', '\x2', '\x2', '\xDC', 
		'\xC6', '\x3', '\x2', '\x2', '\x2', '\xDD', '\xE0', '\x3', '\x2', '\x2', 
		'\x2', '\xDE', '\xDC', '\x3', '\x2', '\x2', '\x2', '\xDE', '\xDF', '\x3', 
		'\x2', '\x2', '\x2', '\xDF', '\r', '\x3', '\x2', '\x2', '\x2', '\xE0', 
		'\xDE', '\x3', '\x2', '\x2', '\x2', '\x16', '\x15', '\x1B', '#', '/', 
		'\x34', '\x43', '\x45', 'S', 'X', 'p', 'z', '\x82', '\x86', '\x97', '\xAF', 
		'\xC9', '\xD3', '\xD8', '\xDC', '\xDE',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
